export const FORECAST_FETCH_START = 'FORECAST_FETCH_START';
export const FORECAST_FETCH_SUCCESS = 'FORECAST_FETCH_SUCCESS';
export const FORECAST_FETCH_FAIL = 'FORECAST_FETCH_FAIL';

export const CURRENT_WEATHER_FETCH_START = 'CURRENT_WEATHER_FETCH_START';
export const CURRENT_WEATHER_FETCH_SUCCESS = 'CURRENT_WEATHER_FETCH_SUCCESS';
export const CURRENT_WEATHER_FETCH_FAIL = 'CURRENT_WEATHER_FETCH_FAIL';

export const FAVORITES_WEATHER_FETCH_START = 'FAVORITES_WEATHER_FETCH_START';
export const FAVORITES_WEATHER_FETCH_SUCCESS = 'FAVORITES_WEATHER_FETCH_SUCCESS';
export const FAVORITES_WEATHER_FETCH_FAIL = 'FAVORITES_WEATHER_FETCH_FAIL';

export const SET_LOCATION_NAME = 'SET_LOCATION_NAME';
export const SET_LOCATION_KEY = 'SET_LOCATION_KEY';
export const CHECK_FAVOTIRE_LOCATIONS = 'CHECK_FAVOTIRE_LOCATIONS';
export const ADD_FAVOTIRE_LOCATIONS = 'ADD_FAVOTIRE_LOCATIONS';

export const SWITCH_BETWEEN_METRIC_IMPERIAL = 'SWITCH_METRIC_IMPERIAL';

export const REMOVE_SHOWN_ERROR = 'REMOVE_SHOWN_ERROR';

export const CUSTOM_ERROR_EVENT_HANDLER = 'CUSTOM_ERROR_EVENT_HANDLER';

export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';